apiVersion: v1
kind: Service
metadata:
  name: go-heif-api
  labels:
    app: go-heif-api
spec:
  type: ClusterIP
  selector:
    app: go-heif-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
